# Generated by Django 4.0.1 on 2022-03-06 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='image_url',
            new_name='img_url',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='categories',
        ),
    ]
